### ISSUE TITLE
Rate limiting on operations

### ISSUE THREAD

**Issue by dholms** [did-method-plc/did-method-plc#20]
Operations that fork history should probably be allowed without any rate limit.

Otherwise we should probably have pretty aggressive rate limits per-did. Perhaps one operation every 5 minutes? Longer?

**Comment by bnewbold** [comment]
The work in the atproto repo might be re-usable. Particularly the headers to communicate issues.

Probably want relatively generous global and per-CIDR-network (basically per IP) DID creation limit (with bypass). Distinct from any per-DID limits. Maybe 2k/day?

Then per-DID, I was thinking the limit should be "ops per-DID, per-signing-key". This means a fork is always possible (distinct key). There is a loophole where somebody could keep creating new keys and signing with those to evade limit, but that is pretty high-effort. Maybe 25 ops/day? This can (should?) be enforced by looking just at the existing database, don't need an external rate-limit store. But could also be done with redis if easier.

Your idea of "aggressive recovery always allowed" then do op rate limits also makes sense, and might be easier to implement, though it has the same sort of high-effort loophole/bypass.

**Comment by bnewbold** [comment]
We got in basic rate-limits a while back.
