### ISSUE TITLE
review/tweak DID document `@context`

### ISSUE THREAD

**Issue by bnewbold** [did-method-plc/did-method-plc#32]
As pointed out in our W3C registration review: https://github.com/w3c/did-spec-registries/pull/515#issuecomment-1572661015

The JSON-LD `@context` links don't seem to be quite right. In particular `https://w3id.org/security/suites/ecdsa-2019/v1` is a 404.

cc: @dholms 

OR13 linked to other URLs. We should do all of:

- [ ] include the correct URLs in our DID document `@context`, for all the key types we support
- [ ] verify our DID document output is valid JSON-LD using some automated tooling
- [ ] update docs (README in this repo, possibly elsewhere)
- [ ] update test files/vectors in other repos (atproto and indigo)
- [ ] update any did:web docs/examples/tests as well
- [ ] communicate these changes to dev community

**Comment by dholms** [comment]
hmmm i remember looking around for a long time for the proper @context for P-256 😅 

the one they linked is for k256

but yeah 404 is no good, probably some more shopping around needed

**Comment by bnewbold** [comment]
Ok, this took a while to hunt down, and i'm not :100: I nailed it.

Support for the `EcdsaSecp256r1VerificationKey2019` type (for P-256 keys; used in our docs/examples but not much in prod) disappeared between two drafts of the same doc, which made searching hard:

```
ECDSA Cryptosuite v2019
Achieving Data Integrity using ECDSA with NIST-compliant curves
Final Community Group Report 24 July 2022
https://www.w3.org/community/reports/credentials/CG-FINAL-di-ecdsa-2019-20220724/
```
and
```
Data Integrity ECDSA Cryptosuites v1.0
Achieving Data Integrity using ECDSA with NIST-compliant curves
W3C Working Draft 23 July 2023
```

What seems to have happened is they switched over to `Multikey` generically. [Example with both P-256 and P-384 keys](https://www.w3.org/TR/vc-di-ecdsa/#example-two-public-keys-p-256-and-p-384-encoded-as-multikeys-in-a-controller-document), where it is the multikey prefix which indicates the key type. Either of https://w3id.org/security/data-integrity/v1 or https://w3id.org/security/multikey/v1 might work in `@context`.

I can't find an actual example with a K-256 curve using `Multikey` as a type, but assume that is a direction thing are moving in: having it multikey indicate the type, not the `type` field.

**Comment by bnewbold** [comment]
I'm closing this for now. There is still a lingering TODO around one of the security suites, but that is now just waiting on W3C standardization.
