### ISSUE TITLE
DID Document hosting/retrieval and managing the latest state

### ISSUE THREAD

**Issue by alenhorvat** [did-method-plc/did-method-plc#35]
Hi.

If my understanding is correct, currently the DID operations are validated by a "central PLC directory server".
From the description and the use of CIDv1, I guess the DID Documents are/can be stored on IPFS. 
Since all the operations are signed, everyone can verify the history of changes.

Role of the PLC server is to validate the changes and to maintain the latest valid state of the DID Document?

Is my understanding correct?

If so, is there a plan/vision to establish a network of "trusted witnesses" (like the PLC server; all witnesses need to adhere to the same rules) that would enable to establish a global network for did:plc that could be then used by any application/system?

**Comment by bnewbold** [comment]
Mostly correct:

* currently there is a central PLC directory server
* we use some IPFS tech (IPLD dag-cbor, CIDs, etc), but nothing is actually stored in the IPFS network or transferred over the IPFS network protocol. Everything is currently in a simple SQL database
* the PLC server accepts valid PLC operations, which must be signed with a currently-valid key (according to the rules outlined in the spec), and then stores the operation. when returning DID Documents, the server computes the document based on the current state of the DID metadata (according to the rules in the spec)
* there is a vision to have more parties involved, either as mirrors, observers, auditors, etc. the did:plc method was designed to make this possible. however, nobody is currently working on this vision and there is no specific roadmap. interested in giving it a try?

**Comment by bnewbold** [comment]
I'm going to close this as resolved, feel free to re-open if you have any other questions.
