### ISSUE TITLE
OpenAPI Spec wrong: `DidDocument.verificationMethods` should be `verificationMethod`

### ISSUE THREAD

**Issue by philipp-eisen** [did-method-plc/did-method-plc#82]
The [OpenAPI Spec](https://github.com/did-method-plc/did-method-plc/blob/main/website/spec/plc-server-openapi3.yaml#L417) defines the response of `GET /https://plc.directory/{did}` to contain `verificationMethods` however the server responds with `verificationMethod`.

Also the provided client uses `verificationMethod`.
https://github.com/did-method-plc/did-method-plc/blob/main/packages/lib/src/types.ts#L103

**Comment by bnewbold** [comment]
thanks for reporting!
